/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "primary": "#0c412d",
        "primary-container": "#285943",
        "on-primary": "#ffffff",
        "on-primary-container": "#9aceb2",
        "primary-fixed": "#b9eed1",
        "primary-fixed-dim": "#9ed2b6",
        "on-primary-fixed": "#002114",
        "on-primary-fixed-variant": "#1e4f3a",
        "secondary": "#875200",
        "secondary-container": "#ffad45",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#6f4300",
        "secondary-fixed": "#ffddba",
        "secondary-fixed-dim": "#ffb865",
        "on-secondary-fixed": "#2b1700",
        "on-secondary-fixed-variant": "#673d00",
        "tertiary": "#672200",
        "tertiary-container": "#863814",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffaf8f",
        "tertiary-fixed": "#ffdbce",
        "tertiary-fixed-dim": "#ffb598",
        "on-tertiary-fixed": "#370e00",
        "on-tertiary-fixed-variant": "#7a2f0b",
        "accent": "#D88C24",
        "background": "#fcf9f8",
        "on-background": "#1b1c1c",
        "surface": "#fcf9f8",
        "surface-bright": "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-tint": "#376851",
        "on-surface": "#1b1c1c",
        "on-surface-variant": "#414943",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e4e2e1",
        "surface-variant": "#e4e2e1",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f3f0ef",
        "inverse-primary": "#9ed2b6",
        "outline": "#717973",
        "outline-variant": "#c0c9c1",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a"
      },
      fontFamily: {
        "display": ['Fraunces', 'serif'],
        "headline": ['Fraunces', 'serif'],
        "body": ['Plus Jakarta Sans', 'sans-serif'],
        "label": ['Plus Jakarta Sans', 'sans-serif'],
        "display-lg": ['Fraunces', 'serif'],
        "headline-lg": ['Fraunces', 'serif'],
        "headline-lg-mobile": ['Fraunces', 'serif'],
        "headline-md": ['Fraunces', 'serif'],
        "body-lg": ['Plus Jakarta Sans', 'sans-serif'],
        "body-md": ['Plus Jakarta Sans', 'sans-serif'],
        "label-md": ['Plus Jakarta Sans', 'sans-serif'],
        "label-sm": ['Plus Jakarta Sans', 'sans-serif']
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }]
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "base": "8px",
        "gutter-desktop": "24px",
        "margin-desktop": "80px",
        "margin-mobile": "20px"
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.5rem',
        full: '9999px'
      },
      maxWidth: {
        'xs': '20rem',
        'sm': '24rem',
        'md': '28rem',
        'lg': '32rem',
        'xl': '36rem',
        '2xl': '42rem',
        '3xl': '48rem',
        '4xl': '56rem',
        '5xl': '64rem',
        '6xl': '72rem',
        '7xl': '80rem',
      },
      boxShadow: {
        'ambient': '0px 4px 20px rgba(40, 89, 67, 0.08)',
        'ambient-sm': '0px 4px 20px rgba(40, 89, 67, 0.04)'
      }
    },
  },
  plugins: [],
}
